accounts: 
  - api_key: 2fcec2bd1c112dad755fbe1ad54db878
    submission_interval: 1
    jobs:
      - id: merchant_16_job
        plugin: plugin_fd
        config:
          board:
            name: Merchant 16
            prefix: m16