accounts: 
  - api_key: 3b679e118a1979c4bae255f7d2a9c858
    submission_interval: 1
    jobs:
      - id: merchant_1_job
        plugin: plugin_fd
        config:
          board:
            name: Merchant 1
            prefix: m1
      - id: merchant_2_job
        plugin: plugin_fd
        config:
          board:
            name: Merchant 2
            prefix: m2